resources:
  containers:
    - container: rust-mkl
      image: rustmath/mkl:latest

jobs:
  - template: ci/job.yml
    parameters:
      name: Linux
      pool:
        vmImage: 'ubuntu-16.04'

  - template: ci/job.yml
    parameters:
      name: macOS
      pool:
        vmImage: 'macOS-10.14'

  - job: 'pkg_config'
    pool:
      vmImage: 'ubuntu-16.04'
    container: rust-mkl
    steps:
      - script: cargo test --verbose
