[package]
name = "intel-mkl-tool"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[features]
default = ["cli"]
cli = ["structopt", "env_logger"]

[dependencies]
curl = "0.4.25"
failure = "0.1.6"
pkg-config = "0.3.17"
tar = "0.4.26"
log = "0.4.8"
dirs = "2.0.2"
glob = "0.3.0"
zstd = "0.5.1"

# CLI
structopt  = { version = "0.3.5", optional = true }
env_logger = { version = "0.7.1", optional = true }

[[bin]]
name = "intel-mkl-tool"
path = "src/cli.rs"
required-features = ["cli"]
