[package]
name = "intel-mkl-sys"
version = "2019.5.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[dependencies.intel-mkl-src]
path = "../intel-mkl-src"

[dev-dependencies]
criterion = "0.3"
rand = "0.7"
approx = "0.3"

[[bench]]
name = "cos"
harness = false
