name: docker

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  rust:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build and push docker image
      run: |
        echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        make -C docker push/rust

  centos:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build and push docker image
      run: |
        echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        make -C docker push/centos

  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build and push docker image
      run: |
        echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        make -C docker push/ubuntu
