name: intel-mkl-tool

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.56.0"
        profile: minimal
        default: true
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=intel-mkl-tool/Cargo.toml
      name: cargo-test
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=intel-mkl-tool/Cargo.toml --no-default-features
      name: cargo-test no-default-features

  docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: ["test", "package", "seek", "seek-ubuntu", "seek-centos"]
    steps:
    - uses: actions/checkout@v1
    - name: Test with mkl-rust container
      run: make -C intel-mkl-tool ${{ matrix.target }}

  seek-opt-intel:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rust-math/intel-mkl-src/mkl-rust:1.56.0
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      name: cargo test seek_opt_intel
      with:
        command: test
        args: >
          --manifest-path=intel-mkl-tool/Cargo.toml
          seek_opt_intel
          --
          --ignored
          --show-output
