name: intel-mkl-tool

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.56.0"
        profile: minimal
        default: true
        override: true
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=intel-mkl-tool/Cargo.toml
    - name: cargo test with no-default-features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --manifest-path=intel-mkl-tool/Cargo.toml
          --no-default-features

  seek:
    strategy:
      fail-fast: false
      matrix:
        image:
          - mkl-rust
          - mkl-ubuntu
          - mkl-centos
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rust-math/intel-mkl-src/${{ matrix.image }}:1.56.0
    steps:
    - uses: actions/checkout@v1
    - name: cargo run -- seek
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: >
          --manifest-path=intel-mkl-tool/Cargo.toml
          -- seek
