name: intel-mkl-sys

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
          - rust:1.62.1
        feature:
          - mkl-static-lp64-iomp
          - mkl-static-lp64-seq
          - mkl-static-ilp64-iomp
          - mkl-static-ilp64-seq
        include:
          - image: ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
            feature: mkl-dynamic-lp64-iomp
          - image: ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
            feature: mkl-dynamic-lp64-seq
          - image: ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
            feature: mkl-dynamic-ilp64-iomp
          - image: ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
            feature: mkl-dynamic-ilp64-seq
    runs-on: ubuntu-22.04
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/cargo@v1
        if: matrix.image == 'rust:1.62.1'
        with:
          command: install
          args: ocipkg-cli --version=0.2.3
      - name: Login to ghcr.io
        if: matrix.image == 'rust:1.62.1'
        run: |
          ocipkg login -u ${{ github.repository_owner }} -p ${{ github.token }} https://ghcr.io

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=intel-mkl-sys/Cargo.toml
            --no-default-features
            --features=${{ matrix.feature }}
