name: intel-mkl-tool

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - macos-11
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.61.0
        profile: minimal
        default: true
        override: true
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=intel-mkl-tool/Cargo.toml

  seek:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rust-math/rust-mkl:1.62.1-2020.1
    steps:
    - uses: actions/checkout@v1
    - name: Run seek example
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: >
          --manifest-path=intel-mkl-tool/Cargo.toml
          --release
          --example seek

  seek-apt:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:22.04
          - ubuntu:20.04
          - debian:10
    container:
      image: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v1

    - name: Add non-free registry
      if: ${{ startsWith(matrix.image, 'debian') }}
      run: sed -i "s/main$/main contrib non-free/" /etc/apt/sources.list

    - name: Install MKL using apt
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt install -y intel-mkl curl gcc

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.61.0
        profile: minimal
        default: true
        override: true
    - name: Run seek example
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: >
          --manifest-path=intel-mkl-tool/Cargo.toml
          --release
          --example seek
